[phases.setup]
nixPkgs = ["ffmpeg", "python312", "which"]

[phases.install]
cmds = ["pip install yt-dlp flask flask-cors gunicorn"]

[start]
cmd = "gunicorn grabmax_server:app --bind 0.0.0.0:$PORT --workers 1 --timeout 300"
